"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { Campaign } from "@/types/database";

export default function CampaignsBoard() {
  const supabase = createClient();
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [showGen, setShowGen] = useState(false);
  const [goal, setGoal] = useState("");
  const [generating, setGenerating] = useState(false);
  const [pending, setPending] = useState<{ name: string; steps: any[] } | null>(null);

  async function load() {
    const { data } = await supabase.from("campaigns").select("*").order("created_at", { ascending: false });
    setCampaigns((data ?? []) as any);
  }
  useEffect(() => { load(); }, []);

  async function generate() {
    setGenerating(true);
    setPending(null);
    const res = await fetch("/api/ai/generate-campaign", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ goal }) });
    const body = await res.json();
    if (res.ok) setPending(body); else alert(body.error);
    setGenerating(false);
  }

  async function save() {
    if (!pending) return;
    const { data: { user } } = await supabase.auth.getUser();
    const { data: membership } = await supabase.from("org_members").select("org_id, id").eq("user_id", user!.id).single();
    await supabase.from("campaigns").insert({ org_id: membership!.org_id, name: pending.name, description: "Generated by AI", steps: pending.steps, created_by: membership!.id });
    setShowGen(false); setPending(null); setGoal("");
    load();
  }

  async function enrollNewLeads(campaignId: string) {
    const { data: { user } } = await supabase.auth.getUser();
    const { data: membership } = await supabase.from("org_members").select("org_id").eq("user_id", user!.id).single();
    const { data: firstStage } = await supabase.from("pipeline_stages").select("id").order("sort_order").limit(1).single();
    const { data: targets } = await supabase.from("leads").select("id").eq("stage_id", firstStage!.id).is("campaign_id", null);
    if (!targets || targets.length === 0) { alert("No unenrolled new leads to add"); return; }

    for (const lead of targets) {
      await supabase.from("leads").update({ campaign_id: campaignId }).eq("id", lead.id);
      await supabase.from("campaign_enrollments").insert({ org_id: membership!.org_id, campaign_id: campaignId, lead_id: lead.id });
      await supabase.from("lead_activities").insert({ org_id: membership!.org_id, lead_id: lead.id, activity_type: "note", feedback: "Enrolled in AI campaign" });
    }
    alert(`${targets.length} lead(s) enrolled`);
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-2">
        <h1 className="font-serif text-2xl font-semibold">AI Campaigns</h1>
      </div>
      <p className="text-sm text-ink/60 max-w-xl mb-6">
        Describe a goal, AI drafts a multi-step WhatsApp/email sequence, you review and save it, then enroll matching leads.
        Note: this prototype logs enrollment — actually sending each step on schedule needs a cron-triggered Edge Function (see README).
      </p>

      <div className="grid md:grid-cols-3 gap-4">
        <button onClick={() => setShowGen(true)} className="border-2 border-dashed border-line rounded-lg p-6 text-sm font-semibold text-ink/50 hover:text-ink hover:border-brass">
          + New AI campaign
        </button>
        {campaigns.map((c) => (
          <div key={c.id} className="bg-white border border-line rounded-lg p-4">
            <h3 className="font-semibold mb-1">{c.name}</h3>
            <p className="text-xs text-ink/50 mb-3">{c.description}</p>
            <div className="space-y-2 mb-3">
              {c.steps.map((s, i) => (
                <div key={i} className="flex gap-2 text-xs">
                  <span className="bg-ink/5 rounded px-1.5 h-fit font-bold">Day {s.day}</span>
                  <div><span className="font-bold capitalize">{s.channel}</span>{s.subject ? ` — ${s.subject}` : ""}<div className="text-ink/50">{s.message}</div></div>
                </div>
              ))}
            </div>
            <button onClick={() => enrollNewLeads(c.id)} className="text-xs font-semibold border border-line rounded-md px-3 py-1.5">Enroll new leads</button>
          </div>
        ))}
      </div>

      {showGen && (
        <div className="fixed inset-0 bg-ink/40 flex items-center justify-center z-50 p-5" onClick={(e) => e.target === e.currentTarget && setShowGen(false)}>
          <div className="bg-white rounded-xl p-6 w-full max-w-lg">
            <h3 className="font-semibold mb-3">Generate a campaign with AI</h3>
            <textarea value={goal} onChange={(e) => setGoal(e.target.value)} placeholder="e.g. Re-engage leads who visited a site 2+ weeks ago but haven't booked"
              className="w-full border border-line rounded-md px-3 py-2 mb-3 text-sm min-h-[70px]" />
            <div className="flex justify-end mb-4">
              <button onClick={generate} disabled={generating} className="bg-brass text-white text-sm font-semibold rounded-md px-4 py-2">
                {generating ? "Generating…" : "Generate"}
              </button>
            </div>
            {pending && (
              <>
                <div className="space-y-2 mb-4">
                  {pending.steps.map((s, i) => (
                    <div key={i} className="flex gap-2 text-xs">
                      <span className="bg-ink/5 rounded px-1.5 h-fit font-bold">Day {s.day}</span>
                      <div><span className="font-bold capitalize">{s.channel}</span>{s.subject ? ` — ${s.subject}` : ""}<div className="text-ink/50">{s.message}</div></div>
                    </div>
                  ))}
                </div>
                <div className="flex justify-end"><button onClick={save} className="bg-brass text-white text-sm font-semibold rounded-md px-4 py-2">Save campaign: {pending.name}</button></div>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
